default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root123
  host: mysql

development:
  <<: *default
  database: bank_development

test:
  <<: *default
  database: bank_test

production:
  <<: *default
  database: bank_production
  username: bank
  password: <%= ENV['BANK_DATABASE_PASSWORD'] %>
